package info.laht.threekt.renderers.shaders

import info.laht.threekt.renderers.shaders.chunk.*
import info.laht.threekt.renderers.shaders.lib.*

object ShaderChunk {

    operator fun get(name: String): String {
        return map.getValue(name)
    }

    private val map = mutableMapOf(
        "alphamap_fragment" to __alphamap_fragment,
        "alphamap_pars_fragment" to __alphamap_pars_fragment,
        "alphatest_fragment" to __alphatest_fragment,
        "aomap_fragment" to __aomap_fragment,
        "aomap_pars_fragment" to __aomap_pars_fragment,
        "beginnormal_vertex" to __beginnormal_vertex,
        "begin_vertex" to __begin_vertex,
        "bsdfs" to __bsdfs,
        "bumpmap_pars_fragment" to __bumpmap_pars_fragment,
        "clipping_planes_fragment" to __clipping_planes_fragment,
        "clipping_planes_pars_fragment" to __clipping_planes_pars_fragment,
        "clipping_planes_pars_vertex" to __clipping_planes_pars_vertex,
        "clipping_planes_vertex" to __clipping_planes_vertex,
        "color_fragment" to __color_fragment,
        "color_pars_fragment" to __color_pars_fragment,
        "color_pars_vertex" to __color_pars_vertex,
        "color_vertex" to __color_vertex,
        "common" to __common,
        "cube_uv_reflection_fragment" to __cube_uv_reflection_fragment,
        "defaultnormal_vertex" to __defaultnormal_vertex,
        "default_fragment" to __default_fragment,
        "default_vertex" to __default_vertex,
        "displacementmap_pars_vertex" to __displacementmap_pars_vertex,
        "displacementmap_vertex" to __displacementmap_vertex,
        "dithering_fragment" to __dithering_fragment,
        "dithering_pars_fragment" to __dithering_pars_fragment,
        "emissivemap_fragment" to __emissivemap_fragment,
        "emissivemap_pars_fragment" to __emissivemap_pars_fragment,
        "encodings_fragment" to __encodings_fragment,
        "encodings_pars_fragment" to __encodings_pars_fragment,
        "envmap_fragment" to __envmap_fragment,
        "envmap_pars_fragment" to __envmap_pars_fragment,
        "envmap_pars_vertex" to __envmap_pars_vertex,
        "envmap_physical_pars_fragment" to __envmap_physical_pars_fragment,
        "envmap_vertex" to __envmap_vertex,
        "fog_fragment" to __fog_fragment,
        "fog_pars_fragment" to __fog_pars_fragment,
        "fog_pars_vertex" to __fog_pars_vertex,
        "fog_vertex" to __fog_vertex,
        "gradientmap_pars_fragment" to __gradientmap_pars_fragment,
        "lightmap_fragment" to __lightmap_fragment,
        "lightmap_pars_fragment" to __lightmap_pars_fragment,
        "lights_fragment_begin" to __lights_fragment_begin,
        "lights_fragment_end" to __lights_fragment_end,
        "lights_fragment_maps" to __lights_fragment_maps,
        "lights_lambert_vertex" to __lights_lambert_vertex,
        "lights_pars_begin" to __lights_pars_begin,
        "lights_phong_fragment" to __lights_phong_fragment,
        "lights_phong_pars_fragment" to __lights_phong_pars_fragment,
        "lights_physical_fragment" to __lights_physical_fragment,
        "lights_physical_pars_fragment" to __lights_physical_pars_fragment,
        "logdepthbuf_fragment" to __logdepthbuf_fragment,
        "logdepthbuf_pars_fragment" to __logdepthbuf_pars_fragment,
        "logdepthbuf_pars_vertex" to __logdepthbuf_pars_vertex,
        "logdepthbuf_vertex" to __logdepthbuf_vertex,
        "map_fragment" to __map_fragment,
        "map_pars_fragment" to __map_pars_fragment,
        "map_particle_fragment" to __map_particle_fragment,
        "map_particle_pars_fragment" to __map_particle_pars_fragment,
        "metalnessmap_fragment" to __metalnessmap_fragment,
        "metalnessmap_pars_fragment" to __metalnessmap_pars_fragment,
        "morphnormal_vertex" to __morphnormal_vertex,
        "morphtarget_pars_vertex" to __morphtarget_pars_vertex,
        "morphtarget_vertex" to __morphtarget_vertex,
        "normalmap_pars_fragment" to __normalmap_pars_fragment,
        "normal_fragment_begin" to __normal_fragment_begin,
        "normal_fragment_maps" to __normal_fragment_maps,
        "packing" to __packing,
        "premultiplied_alpha_fragment" to __premultiplied_alpha_fragment,
        "project_vertex" to __project_vertex,
        "roughnessmap_fragment" to __roughnessmap_fragment,
        "roughnessmap_pars_fragment" to __roughnessmap_pars_fragment,
        "shadowmap_pars_fragment" to __shadowmap_pars_fragment,
        "shadowmap_pars_vertex" to __shadowmap_pars_vertex,
        "shadowmap_vertex" to __shadowmap_vertex,
        "shadowmask_pars_fragment" to __shadowmask_pars_fragment,
        "skinbase_vertex" to __skinbase_vertex,
        "skinning_pars_vertex" to __skinning_pars_vertex,
        "skinning_vertex" to __skinning_vertex,
        "skinnormal_vertex" to __skinnormal_vertex,
        "specularmap_fragment" to __specularmap_fragment,
        "specularmap_pars_fragment" to __specularmap_pars_fragment,
        "tonemapping_fragment" to __tonemapping_fragment,
        "tonemapping_pars_fragment" to __tonemapping_pars_fragment,
        "uv2_pars_fragment" to __uv2_pars_fragment,
        "uv2_pars_vertex" to __uv2_pars_vertex,
        "uv2_vertex" to __uv2_vertex,
        "uv_pars_fragment" to __uv_pars_fragment,
        "uv_pars_vertex" to __uv_pars_vertex,
        "uv_vertex" to __uv_vertex,
        "worldpos_vertex" to __worldpos_vertex,
        "background_frag" to __background_frag,
        "background_vert" to __background_vert,
        "cube_frag" to __cube_frag,
        "cube_vert" to __cube_vert,
        "depth_frag" to __depth_frag,
        "depth_vert" to __depth_vert,
        "distanceRGBA_frag" to __distanceRGBA_frag,
        "distanceRGBA_vert" to __distanceRGBA_vert,
        "equirect_frag" to __equirect_frag,
        "equirect_vert" to __equirect_vert,
        "linedashed_frag" to __linedashed_frag,
        "linedashed_vert" to __linedashed_vert,
        "meshbasic_frag" to __meshbasic_frag,
        "meshbasic_vert" to __meshbasic_vert,
        "meshlambert_frag" to __meshlambert_frag,
        "meshlambert_vert" to __meshlambert_vert,
        "meshmatcap_frag" to __meshmatcap_frag,
        "meshmatcap_vert" to __meshmatcap_vert,
        "meshphong_frag" to __meshphong_frag,
        "meshphong_vert" to __meshphong_vert,
        "meshphysical_frag" to __meshphysical_frag,
        "meshphysical_vert" to __meshphysical_vert,
        "normal_frag" to __normal_frag,
        "normal_vert" to __normal_vert,
        "points_frag" to __points_frag,
        "points_vert" to __points_vert,
        "shadow_frag" to __shadow_frag,
        "shadow_vert" to __shadow_vert,
        "sprite_frag" to __sprite_frag,
        "sprite_vert" to __sprite_vert
    )

    val alphamap_fragment: String
        get() = __alphamap_fragment
    val alphamap_pars_fragment: String
        get() = __alphamap_pars_fragment
    val alphatest_fragment: String
        get() = __alphatest_fragment
    val aomap_fragment: String
        get() = __aomap_fragment
    val aomap_pars_fragment: String
        get() = __aomap_pars_fragment
    val beginnormal_vertex: String
        get() = __beginnormal_vertex
    val begin_vertex: String
        get() = __begin_vertex
    val bsdfs: String
        get() = __bsdfs
    val bumpmap_pars_fragment: String
        get() = __bumpmap_pars_fragment
    val clipping_planes_fragment: String
        get() = __clipping_planes_fragment
    val clipping_planes_pars_fragment: String
        get() = __clipping_planes_pars_fragment
    val clipping_planes_pars_vertex: String
        get() = __clipping_planes_pars_vertex
    val clipping_planes_vertex: String
        get() = __clipping_planes_vertex
    val color_fragment: String
        get() = __color_fragment
    val color_pars_fragment: String
        get() = __color_pars_fragment
    val color_pars_vertex: String
        get() = __color_pars_vertex
    val color_vertex: String
        get() = __color_vertex
    val common: String
        get() = __common
    val cube_uv_reflection_fragment: String
        get() = __cube_uv_reflection_fragment
    val defaultnormal_vertex: String
        get() = __defaultnormal_vertex
    val default_fragment: String
        get() = __default_fragment
    val default_vertex: String
        get() = __default_vertex
    val displacementmap_pars_vertex: String
        get() = __displacementmap_pars_vertex
    val displacementmap_vertex: String
        get() = __displacementmap_vertex
    val dithering_fragment: String
        get() = __dithering_fragment
    val dithering_pars_fragment: String
        get() = __dithering_pars_fragment
    val emissivemap_fragment: String
        get() = __emissivemap_fragment
    val emissivemap_pars_fragment: String
        get() = __emissivemap_pars_fragment
    val encodings_fragment: String
        get() = __encodings_fragment
    val encodings_pars_fragment: String
        get() = __encodings_pars_fragment
    val envmap_fragment: String
        get() = __envmap_fragment
    val envmap_pars_fragment: String
        get() = __envmap_pars_fragment
    val envmap_pars_vertex: String
        get() = __envmap_pars_vertex
    val envmap_physical_pars_fragment: String
        get() = __envmap_physical_pars_fragment
    val envmap_vertex: String
        get() = __envmap_vertex
    val fog_fragment: String
        get() = __fog_fragment
    val fog_pars_fragment: String
        get() = __fog_pars_fragment
    val fog_pars_vertex: String
        get() = __fog_pars_vertex
    val fog_vertex: String
        get() = __fog_vertex
    val gradientmap_pars_fragment: String
        get() = __gradientmap_pars_fragment
    val lightmap_fragment: String
        get() = __lightmap_fragment
    val lightmap_pars_fragment: String
        get() = __lightmap_pars_fragment
    val lights_fragment_begin: String
        get() = __lights_fragment_begin
    val lights_fragment_end: String
        get() = __lights_fragment_end
    val lights_fragment_maps: String
        get() = __lights_fragment_maps
    val lights_lambert_vertex: String
        get() = __lights_lambert_vertex
    val lights_pars_begin: String
        get() = __lights_pars_begin
    val lights_phong_fragment: String
        get() = __lights_phong_fragment
    val lights_phong_pars_fragment: String
        get() = __lights_phong_pars_fragment
    val lights_physical_fragment: String
        get() = __lights_physical_fragment
    val lights_physical_pars_fragment: String
        get() = __lights_physical_pars_fragment
    val logdepthbuf_fragment: String
        get() = __logdepthbuf_fragment
    val logdepthbuf_pars_fragment: String
        get() = __logdepthbuf_pars_fragment
    val logdepthbuf_pars_vertex: String
        get() = __logdepthbuf_pars_vertex
    val logdepthbuf_vertex: String
        get() = __logdepthbuf_vertex
    val map_fragment: String
        get() = __map_fragment
    val map_pars_fragment: String
        get() = __map_pars_fragment
    val map_particle_fragment: String
        get() = __map_particle_fragment
    val map_particle_pars_fragment: String
        get() = __map_particle_pars_fragment
    val metalnessmap_fragment: String
        get() = __metalnessmap_fragment
    val metalnessmap_pars_fragment: String
        get() = __metalnessmap_pars_fragment
    val morphnormal_vertex: String
        get() = __morphnormal_vertex
    val morphtarget_pars_vertex: String
        get() = __morphtarget_pars_vertex
    val morphtarget_vertex: String
        get() = __morphtarget_vertex
    val normalmap_pars_fragment: String
        get() = __normalmap_pars_fragment
    val normal_fragment_begin: String
        get() = __normal_fragment_begin
    val normal_fragment_maps: String
        get() = __normal_fragment_maps
    val packing: String
        get() = __packing
    val premultiplied_alpha_fragment: String
        get() = __premultiplied_alpha_fragment
    val project_vertex: String
        get() = __project_vertex
    val roughnessmap_fragment: String
        get() = __roughnessmap_fragment
    val roughnessmap_pars_fragment: String
        get() = __roughnessmap_pars_fragment
    val shadowmap_pars_fragment: String
        get() = __shadowmap_pars_fragment
    val shadowmap_pars_vertex: String
        get() = __shadowmap_pars_vertex
    val shadowmap_vertex: String
        get() = __shadowmap_vertex
    val shadowmask_pars_fragment: String
        get() = __shadowmask_pars_fragment
    val skinbase_vertex: String
        get() = __skinbase_vertex
    val skinning_pars_vertex: String
        get() = __skinning_pars_vertex
    val skinning_vertex: String
        get() = __skinning_vertex
    val skinnormal_vertex: String
        get() = __skinnormal_vertex
    val specularmap_fragment: String
        get() = __specularmap_fragment
    val specularmap_pars_fragment: String
        get() = __specularmap_pars_fragment
    val tonemapping_fragment: String
        get() = __tonemapping_fragment
    val tonemapping_pars_fragment: String
        get() = __tonemapping_pars_fragment
    val uv2_pars_fragment: String
        get() = __uv2_pars_fragment
    val uv2_pars_vertex: String
        get() = __uv2_pars_vertex
    val uv2_vertex: String
        get() = __uv2_vertex
    val uv_pars_fragment: String
        get() = __uv_pars_fragment
    val uv_pars_vertex: String
        get() = __uv_pars_vertex
    val uv_vertex: String
        get() = __uv_vertex
    val worldpos_vertex: String
        get() = __worldpos_vertex
    val background_frag: String
        get() = __background_frag
    val background_vert: String
        get() = __background_vert
    val cube_frag: String
        get() = __cube_frag
    val cube_vert: String
        get() = __cube_vert
    val depth_frag: String
        get() = __depth_frag
    val depth_vert: String
        get() = __depth_vert
    val distanceRGBA_frag: String
        get() = __distanceRGBA_frag
    val distanceRGBA_vert: String
        get() = __distanceRGBA_vert
    val equirect_frag: String
        get() = __equirect_frag
    val equirect_vert: String
        get() = __equirect_vert
    val linedashed_frag: String
        get() = __linedashed_frag
    val linedashed_vert: String
        get() = __linedashed_vert
    val meshbasic_frag: String
        get() = __meshbasic_frag
    val meshbasic_vert: String
        get() = __meshbasic_vert
    val meshlambert_frag: String
        get() = __meshlambert_frag
    val meshlambert_vert: String
        get() = __meshlambert_vert
    val meshmatcap_frag: String
        get() = __meshmatcap_frag
    val meshmatcap_vert: String
        get() = __meshmatcap_vert
    val meshphong_frag: String
        get() = __meshphong_frag
    val meshphong_vert: String
        get() = __meshphong_vert
    val meshphysical_frag: String
        get() = __meshphysical_frag
    val meshphysical_vert: String
        get() = __meshphysical_vert
    val normal_frag: String
        get() = __normal_frag
    val normal_vert: String
        get() = __normal_vert
    val points_frag: String
        get() = __points_frag
    val points_vert: String
        get() = __points_vert
    val shadow_frag: String
        get() = __shadow_frag
    val shadow_vert: String
        get() = __shadow_vert
    val sprite_frag: String
        get() = __sprite_frag
    val sprite_vert: String
        get() = __sprite_vert

}
